name: 生成自用Apple TV直播列表

on:
  # push:
    # branches: 
      # - master
  schedule:
    - cron: 30 16 * * *
  watch:
    types: [started]

jobs:
  TV:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true
    - name: Set git identity
      run : |
        git config --global user.email "hououinkami@gmail.com"
        git config --global user.name "hououinkami"
    - name: 国内频道
      run : |
        wget http://tv.sason.xyz/gn.m3u
        awk 'BEGIN{while(getline < "/gn.m3u"){print $0;};close("/etc/passwd");}{gsub("url-tvg=\"http://tv.sason.xyz/epg\"", "")}'>1.m3u
        
        
        
        git add 1.m3u
        git commit -m  "Update"
        git push origin master
