name: 生成自用Apple TV直播列表

on:
  # push:
    # branches: 
      # - master
  schedule:
    - cron: 30 16 * * *
  watch:
    types: [started]

jobs:
  TV:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true
    - name: Set git identity
      run : |
        git config --global user.email "hououinkami@gmail.com"
        git config --global user.name "hououinkami"
    - name: 获取最新源
      run : |
        wget http://tv.sason.xyz/gn.m3u
        wget http://tv.sason.xyz/gt.m3u
        wget https://homenet6.github.io/list.m3u
    - name: 国内频道
      run : >
        awk '
        {
        gsub("url-tvg=\"http://tv.sason.xyz/epg\"", "");
        if($0~"说明") {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {next};
        gsub("A.央视","A 央视频道");
        gsub("B.卫视","B 卫视频道");
        gsub("C.4K频道","Z 4K频道");
        gsub("D.教育频道","C 教育频道");
        gsub("E.数字电视","D 数字电视");
        if($0~/峨眉|四川本地/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {next};
        gsub("FHD|HD|SD","");
        print $0;
        }
        '
        gn.m3u>1.m3u
        
    - name: 合并到仓库
      run : |
        git add 1.m3u
        git commit -m  "Update"
        git push origin master
    - name: 删除源文件
      run : |
        rm gn.m3u
        rm gt.m3u
        rm list.m3u
        ls
