name: 生成自用Apple TV直播列表

on:
  push:
    branches:
      - beta
    path:
      - 'start'
  release:
    types: [published]
  schedule:
    - cron: 0 4,16 * * *
  watch:
    types: [started]

env:
  TZ: Asia/Shanghai
  UPDATE_SOURCE: false
  TV_LIST: http://tv.sason.xyz/new.m3u
  TV_LIST_NAME: new.m3u
  TV_LIST0: http://tv.boye.ml/iptv/tv.m3u
  TV_LIST0_NAME: tv.m3u
  TV_LIST1: https://raw.githubusercontent.com/panda-mute/iptv/master/list.m3u
  TV_LIST1_NAME: list.m3u
  TV_LIST2: https://homenet6.github.io/list.m3u
  TV_LIST2_NAME: list2.m3u
  FOREIGN_LIST: https://raw.githubusercontent.com/hououinkami/AppleTV/master/Foreign.m3u
  FOREIGN_LIST_NAME: Foreign_tmp.m3u
  SCIENCES_LIST: https://raw.githubusercontent.com/hououinkami/AppleTV/master/Sciences.m3u
  SCIENCES_LIST_NAME: Sciences_tmp.m3u
  GROUP_NAME_CCTV: A 央视频道
  GROUP_NAME_SATT: B 卫视频道
  GROUP_NAME_HK: C 香港频道
  GROUP_NAME_MO: E 澳门频道
  GROUP_NAME_TW: D 台湾频道
  GROUP_NAME_JP: F 日本频道
  GROUP_NAME_EN: G 英文频道
  GROUP_NAME_SCI: H 科教记录
  GROUP_NAME_MOV: I 电影轮播

jobs:
  GenerateList:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
        fetch-depth: 0
        lfs: true
    
    - name: Set git identity
      run : |
        git config --global user.email "hououinkami@gmail.com"
        git config --global user.name "hououinkami"
    
    - name: 获取当前日期
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    
    - name: 获取最新源
      run : |
        wget $TV_LIST
        wget $TV_LIST1
        wget $FOREIGN_LIST -O $FOREIGN_LIST_NAME
        wget $SCIENCES_LIST -O $SCIENCES_LIST_NAME
        wget $TV_LIST2 -O $TV_LIST2_NAME
    
    - name: 国内频道(Sason源)
      run : |
        awk '
        {
        if($0~/\#EXTM3U/) {print $0};
        if($0~/央视"|卫视"/ && $0!~/峨眉|潇湘/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          gsub("A.央视","'"$GROUP_NAME_CCTV"'");
          gsub("B.卫视","'"$GROUP_NAME_SATT"'");
          if($0~/深圳/) {gsub("tvg-id=\"[0-9]{1,2}\"","tvg-id=\"26\"")};
          gsub(" FHD| FHD版| HD| SD","")
          print $0;
          };
        }
        ' $TV_LIST_NAME>China.m3u
    
    - name: 港澳台频道(Sason源)
      run : |
        awk '
        {
        if($0~/\#EXTM3U/) {print $0};
        if($0~/香港"|台湾"|澳门"/ && $0!~/CNEX|国家地理|FX Asia/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          gsub("D.香港","'"$GROUP_NAME_HK"'");
          gsub("E.台湾","'"$GROUP_NAME_TW"'");
          gsub("F.澳门","'"$GROUP_NAME_MO"'");
          gsub(" FHD","");
          print $0;
          };
        }
        ' $TV_LIST_NAME>HKTWtmp1.m3u
    
    - name: 香港频道补全
      run : |
        awk '
        {
        if($0~/IPV6|备/) {a=NR; b=NR+1};
        if(a<=NR && NR<=b) {next};
        if($0~/"翡翠台"|"明珠台"/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          if($0~/"翡翠台"|"明珠台"/) {gsub("港台频道","'"$GROUP_NAME_HK"'")};
          print $0;
          };
        }
        ' $TV_LIST1_NAME>HKTWtmp2.m3u
        awk '
        {
        if($0~/备/) {a=NR; b=NR+1};
        if(a<=NR && NR<=b) {next};
        if($0~/无线新闻/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          gsub("港台频道","'"$GROUP_NAME_HK"'");
          print $0;
          };
        }
        ' $TV_LIST2_NAME>HKTWtmp3.m3u

    - name: 生成港澳台频道文件
      run : cat HKTWtmp*.m3u > HKTW.m3u && rm HKTWtmp*.m3u

    - name: 外文频道
      run : |
        awk '
        {
        if($0~/\#EXTM3U/) {print $0};
        gsub("group-title=\"..日本.*\"","group-title=\"'"$GROUP_NAME_JP"'\"");
        gsub("group-title=\"..英文.*\"","group-title=\"'"$GROUP_NAME_EN"'\"");
        print $0;
        }
        ' $FOREIGN_LIST_NAME>Globaltmp1.m3u
        
        awk '
        {
        if($0~/NHK华语视界/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          if($0~/NHK华语视界/) {gsub("group-title=\"*\..*\"","group-title=\"'"$GROUP_NAME_JP"'\"")};
          print $0;
          };
        }
        ' $TV_LIST_NAME>Globaltmp2.m3u

        awk '
        {
        if($0~/IPV6|备/) {a=NR; b=NR+1};
        if(a<=NR && NR<=b) {next};
        if($0~/"体育频道"|"News"/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          if($0~/"体育频道"|"News"/) {gsub("group-title=\"*\..*\"","group-title=\"'"$GROUP_NAME_EN"'\"")};
          print $0;
          };
        }
        ' $TV_LIST1_NAME>Globaltmp3.m3u

    - name: 科学记录频道
      run : |
        awk '
        {
        if($0~/\#EXTM3U/) {print $0};
        gsub("group-title=\"..科教.*\"","group-title=\"'"$GROUP_NAME_SCI"'\"");
        print $0;
        }
        ' $SCIENCES_LIST_NAME>Sciencestmp1.m3u

        awk '
        {
        if($0~/CNEX|国家地理|Discovery|NationalGeographic/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {
          {gsub("group-title=\"*\..*\"","group-title=\"'"$GROUP_NAME_SCI"'\"")};
          print $0;
          };
        }
        ' $TV_LIST_NAME>Sciencestmp2.m3u

        awk '
        {
        if($0~/探索|动物|地理/) {m=NR; n=NR+1};
        if(m<=NR && NR<=n) {gsub("港台频道","'"$GROUP_NAME_SCI"'")};
        print $0;
        }
        ' $TV_LIST1_NAME>Sciencestmp3.m3u

    - name: 生成海外频道文件
      run : cat Globaltmp*.m3u Sciencestmp*.m3u > Global.m3u && rm *tmp*.m3u

    - name: 生成AppleTV总列表
      run : cat China.m3u HKTW.m3u Global.m3u > IPTV.m3u
    
    - name: 删除源文件
      run : |
        rm $TV_LIST_NAME
        rm $TV_LIST1_NAME
        rm $TV_LIST2_NAME
        ls
    
    - name: 判断是否有变更
      id: status
      run: |
        STR1="nothing to commit, working tree clean"
        STR2="Changes not staged for commit"
        out=$(git status)
        if [[ "$(echo $out | grep "$STR1")" != "" ]]
        then
          echo "::set-output name=status::"nochange""
        fi
        if [[ "$(echo $out | grep "$STR2")" != "" ]]
        then
          echo "::set-output name=status::"change""
        fi
    
    - name: 合并到仓库
      run : |
        if [[ "${{steps.status.outputs.status}}" == "change" ]]
        then
          git add .
          git commit -m  "Update:${{steps.date.outputs.date}}"
          git push origin master
        fi
        
